version: '3.7'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - path: .env
volumes:
  postgres_data:
